### ISSUE TITLE
Endpoint for Sandbox Adress API 

### ISSUE THREAD

**Issue by dominik-meissner** [danielneu/amazonpay-alexa-utils#5]
The Endpoint for the Address API in Sandbox mode is _/sandbox/v1/buyer/addresses_ instead of _/SANDBOX/v1/buyer/addresses_

**Comment by dominik-meissner** [comment]
I just realized, the parameter has to be passed in lowercase. I will update docs then. maybe a toLowerCase() is useful here...

**Comment by dominik-meissner** [comment]
JavaScript - that might be the reason.

**Comment by danielneu** [comment]
Typescript enums are case sensitive, so are string type literals.

If you use the Environment enum, that should not be an issue.
I added toLowerCase() where possible to avoid situations like this.

Pushing the update shortly
